export const g_game_data = [
    {
        "id": 219,
        "createdDate": "2024-09-30",
        "title": "Cosmic Defender Space Assault",
        "description": "Take control of your spaceship and fend off incoming enemies\" in this thrilling arcade shooter.\n\nKeyboard: Use arrows to move your ship left or right, space to shoot. Mobile: Use buttons to move your ship, use the red button to fire",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/CC8DT\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/CC8DT\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/cosmic-defender-space-assault\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 11,
        "upvote": 0,
        "downvote": 0,
        "slug": "cosmic-defender-space-assault",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 154,
        "createdDate": "2024-08-19",
        "title": "Whack Zombies",
        "description": "So many zombies are getting closed, get rid of them!",
        "instructions": "",
        "category": "Shooting",
        "source": "self",
        "thumb_1": "https:\/\/tikgame.com\/games\/whack-zombies\/thumb_1.png",
        "thumb_2": "https:\/\/tikgame.com\/games\/whack-zombies\/thumb_2.png",
        "thumb_small": "",
        "url": "https:\/\/tikgame.com\/games\/whack-zombies\/",
        "width": "640",
        "height": "960",
        "tags": "",
        "views": 170,
        "upvote": 0,
        "downvote": 0,
        "slug": "whack-zombies",
        "last_modified": "2024-09-04 18:34:01",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 229,
        "createdDate": "2024-09-30",
        "title": "Scaler Adventure",
        "description": "The game \"Scaler Adventure\" is an interesting puzzle game about a dungeon explorer, a Scaler, and his drone. Resize items to go through all the rooms and send the results to your company. Carry items by drone, thanks to the hook, to activate all the switches and open the main door. Use your logic and ingenuity to the maximum to complete all levels!",
        "instructions": "",
        "category": "Adventure",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/2A91N\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/2A91N\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/scaler-adventure\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 17,
        "upvote": 0,
        "downvote": 0,
        "slug": "scaler-adventure",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 189,
        "createdDate": "2024-09-30",
        "title": "Taxi Empire - Airport Tycoon",
        "description": "Do you want to become the owner of a cool taxi and airport service? This taxi business simulator game is for you! Earn money, unlock new cars and increase their number. Upgrade your airport to carry more people and earn even more!",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/10EAM\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/10EAM\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/taxi-empire-airport-tycoon\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 12,
        "upvote": 0,
        "downvote": 0,
        "slug": "taxi-empire-airport-tycoon",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 209,
        "createdDate": "2024-09-30",
        "title": "Valentine s Day Slider Image Scramble",
        "description": "Welcome to Valentine s Day Slider Image Scramble, a classic puzzle game where players must slide tiles to reassemble a picture. Move the blocks by touching or clicking on them to solve the puzzle.\n\nIn Valentine s Day Slider Image Scramble, players are challenged to solve the puzzle by sliding tiles to reassemble a picture. The objective of the game is to move the blocks by touching or clicking on them until the picture is complete. Welcome to Valentine s Day Slider Image Scramble and enjoy solving the puzzle.",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/AASAA\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/AASAA\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/valentine-s-day-slider-image-scramble\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 7,
        "upvote": 0,
        "downvote": 0,
        "slug": "valentine-s-day-slider-image-scramble",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 204,
        "createdDate": "2024-09-30",
        "title": "The Prison Escape",
        "description": "Prisoners have escaped from your grasp! Hop in the car and chase after them. Beware of the treacherous pathway surrounded by cliffs! Put the caught prisoners back to work.\n",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/ICA70\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/ICA70\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/the-prison-escape\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 14,
        "upvote": 0,
        "downvote": 0,
        "slug": "the-prison-escape",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 216,
        "createdDate": "2024-09-30",
        "title": "Basketball Arena Ultimate Hoops Showdown  ",
        "description": " Aim and Flick the Mouse to Shoot the Ball!\n\n\t.\tStart by pressing the left button anywhere on the screen.\n\t.\tWhile holding down the button, slide it to increase the power of your ball throw.\n\t.\tRelease the button to throw the ball.\nRemember, you only have three ball throws per level, so use them wisely!\nEnjoy the game and make those shots count!\n",
        "instructions": "",
        "category": "Sports",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/5755T\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/5755T\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/basketball-arena-ultimate-hoops-showdown\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 14,
        "upvote": 0,
        "downvote": 0,
        "slug": "basketball-arena-ultimate-hoops-showdown",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 226,
        "createdDate": "2024-09-30",
        "title": "Poppy Playtime Chapter 3 jigsaw puzzle",
        "description": "Poppy Playtime Chapter 3 puzzle\nthis is the first  game to use this specific format, and image, so it is going to be a brand new experience for all of you.",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/027CL\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/027CL\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/poppy-playtime-chapter-3-puzzle\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 10,
        "upvote": 0,
        "downvote": 0,
        "slug": "poppy-playtime-chapter-3-jigsaw-puzzle",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 205,
        "createdDate": "2024-09-30",
        "title": "Easter Egg Coloring Games",
        "description": "Easter Egg Coloring Games invites you to a painter's paradise! With an endless array of coloring pages featuring animals, nature, and abstract patterns, this game is a dream for coloring enthusiasts. Dive into this coloring journey, mix and match hues, and give each painting your personal touch. Come express yourself in Easter Egg Coloring Games and create your masterpiece!\n\n",
        "instructions": "",
        "category": "Junior",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/G7SG3\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/G7SG3\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/easter-egg-coloring-games\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 8,
        "upvote": 0,
        "downvote": 0,
        "slug": "easter-egg-coloring-games",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 223,
        "createdDate": "2024-09-30",
        "title": "Blocks Dash Jump Square",
        "description": "Navigate a bouncing square through a maze of obstacles for endless fun!\npress the left mouse button or touch the screen on your phone to jump, passing obstacles on your way\n",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/QRLAB\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/QRLAB\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/blocks-dash-jump-square\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 11,
        "upvote": 0,
        "downvote": 0,
        "slug": "blocks-dash-jump-square",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 163,
        "createdDate": "2024-08-31",
        "title": "Flying School",
        "description": "Help cute birds learn to fly. Drag and aim to make them fly from one nest to the other.",
        "instructions": "",
        "category": "Adventure",
        "source": "_gamezop",
        "thumb_1": "https:\/\/static.gamezop.com\/VJOGOyGb9l\/cover.jpg",
        "thumb_2": "https:\/\/static.gamezop.com\/VJOGOyGb9l\/square.png",
        "thumb_small": "",
        "url": "https:\/\/7000.play.gamezop.com\/g\/VJOGOyGb9l",
        "width": "800",
        "height": "600",
        "tags": "",
        "views": 12,
        "upvote": 0,
        "downvote": 0,
        "slug": "flying-school",
        "last_modified": "2024-08-31 00:24:25",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 231,
        "createdDate": "2024-09-30",
        "title": "Help Me Story Tricky",
        "description": "Help Me Story Tricky is a puzzle game with lots of tricky riddles and puzzles. There are over 275 puzzle levels designed to trick the player and test his brain. Think on your feet and think outside the box to solve these puzzles. Anything you see on the screen can be used to fix the problem. All the entertaining Brain Test questions will amaze you!",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/997S7\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/997S7\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/help-me-story-tricky\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 18,
        "upvote": 0,
        "downvote": 0,
        "slug": "help-me-story-tricky",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 227,
        "createdDate": "2024-09-30",
        "title": "Pac Rush Man",
        "description": "Pac-Man\" is a classic arcade game originally released by Namco in 1980. It quickly became one of the most iconic and recognizable video games of all time. In \"Pac-Man,\" players control the titular character, a yellow, circular creature with a large mouth, navigating through a maze-like grid filled with dots or pellets.",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/U10NH\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/U10NH\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/pac-rush-man\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 16,
        "upvote": 0,
        "downvote": 0,
        "slug": "pac-rush-man",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 188,
        "createdDate": "2024-09-30",
        "title": "Hero Birds Hidden Stars",
        "description": "Hero Birds Hidden Stars is a free online kids and hidden object game. Find out the hidden stars in the specified images. Each level has 10 hidden stars. There are 8 levels in total. The time is limited so be fast and find all hidden objects before time runs out. Clicking in the wrong place several times reduces the time by an additional 5 seconds. So, if you are ready ",
        "instructions": "",
        "category": "Strategy",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/D8DA2\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/D8DA2\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/hero-birds-hidden-stars\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 13,
        "upvote": 0,
        "downvote": 0,
        "slug": "hero-birds-hidden-stars",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 159,
        "createdDate": "2024-07-10",
        "title": "Ninja Fruit Slice",
        "description": "Ninja Fruit Slice is a classic arcade game. The rule is simple, slice every fruit but not the bomb. You are going to be the fruit ninja and cut up as many fruits as possible to win a high score. Don't slice bombs or miss fruit.",
        "instructions": "On PC\nDrag the mouse to cut.\nOn mobile\nSlide the screen to cut.",
        "category": "Arcade",
        "source": "_4j",
        "thumb_1": "https:\/\/www.4j.com\/thumb\/202405\/Ninja-Fruit-Slice.jpg",
        "thumb_2": "https:\/\/www.4j.com\/thumb\/202405\/Ninja-Fruit-Slice.jpg",
        "thumb_small": "",
        "url": "https:\/\/www.freegames.com\/games\/Ninja-Fruit-Slice\/index.html",
        "width": "1920",
        "height": "1080",
        "tags": "",
        "views": 133,
        "upvote": 0,
        "downvote": 0,
        "slug": "ninja-fruit-slice",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 237,
        "createdDate": "2024-09-30",
        "title": "Police Craft Block Car Race",
        "description": "Take the wheel of your blocky police vehicle in this adrenaline-fueled mobile game! Race against other players, showcasing your speed and skill to emerge victorious.\nNavigate through dynamic environments, dodging obstacles and outmaneuvering opponents to claim the top spot. Are you ready to show off your driving prowess and dominate the competition\n\nUse left and right arrows to rotate your police Car in the Air. press up to accelerate",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/2CELL\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/2CELL\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/police-craft-block-car-race\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 11,
        "upvote": 0,
        "downvote": 0,
        "slug": "police-craft-block-car-race",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 169,
        "createdDate": "2024-09-30",
        "title": "Merge Town!",
        "description": "Ever wanted to be Mayor? Ever wanted to run a town, develop the land, and see a metropolis grow? Well, look no further than Merge Town!, the newest title from Gram Games. The concept of the game is simple - you have a plot of land, and it\u2019s your job to turn it into a town. Every so often, you\u2019ll be gifted with a house. Each house can be merged with other houses of the same variety to form a bigger home.",
        "instructions": "Tap to play, click to merge",
        "category": "Puzzle,Strategy",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/1c726ea44ef646cdac297eb74563ad8e-512x384.jpeg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/1c726ea44ef646cdac297eb74563ad8e-512x512.jpeg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/1c726ea44ef646cdac297eb74563ad8e\/",
        "width": "750",
        "height": "1334",
        "tags": "logic,matching,timekiller,clicker,3d,Kids Friendly,No Blood,No Cruelty",
        "views": 8,
        "upvote": 0,
        "downvote": 0,
        "slug": "merge-town",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 215,
        "createdDate": "2024-09-30",
        "title": "Pomni Circus Ball Toy Collector",
        "description": "Join the Digital Circus Ball on its journey through a whimsical world of circus wonders! Help the playful little black ball collect pomni toys while navigating through thrilling challenges. Fun for all ages\n\nKeyboard: Use the left and right arrows to move your character\nMobile: Touch the left or right side button to move your character",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/YOTR0\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/YOTR0\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/pomni-circus-ball-toy-collector\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 10,
        "upvote": 0,
        "downvote": 0,
        "slug": "pomni-circus-ball-toy-collector",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 206,
        "createdDate": "2024-09-30",
        "title": "Christmas Mandala Coloring Book",
        "description": "Calling all coloring connoisseurs! Christmas Mandala Coloring Book is the quintessential coloring game that blends fun with relaxation. Whether you're into doodling, painting, or coloring, this game has it all. With an easy-to-navigate interface and a vast selection of coloring pages, Christmas Mandala Coloring Book is perfect for artists of every skill level.\n\n",
        "instructions": "",
        "category": "Junior",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/AMSI1\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/AMSI1\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/christmas-mandala-coloring-book\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 14,
        "upvote": 0,
        "downvote": 0,
        "slug": "christmas-mandala-coloring-book",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 199,
        "createdDate": "2024-09-30",
        "title": "Stellar Style Spectacle Fashion",
        "description": "Stellar Style Spectacle Fashion invites you to prep four besties for a futuristic red carpet bash. Your mission: choose attention-grabbing outfits from a virtual wardrobe of holographic gowns, metallic accessories, experiment with gravity-defying hairstyles, and glowing-in-the-dark makeup, and avant-garde accessories. Immerse yourself in a world of creativity, innovation, and stellar fashion. Ready to make a statement on the most spectacular runway of the future? let the fashion spectacle begin!",
        "instructions": "",
        "category": "Junior",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/7R2A9\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/7R2A9\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/stellar-style-spectacle-fashion\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 9,
        "upvote": 0,
        "downvote": 0,
        "slug": "stellar-style-spectacle-fashion",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 166,
        "createdDate": "2024-09-30",
        "title": "Paperly - Paper Plane Adventure",
        "description": "Go on an exciting paper plane flight adventure, learn different flight mechanics &amp; reach your destination.\n\nPAPERLY: PAPER PLANE ADVENTURE - is all about Flying a Paper Plane, learning from previous mistakes, and Heading toward a Better Flight in this Physics-Driven Gameplay.",
        "instructions": "For PC - 'WASD' &amp; 'Shift' for Movements and Boost\n\nFor Mobile - Joystick &amp; Buttons",
        "category": "Adventure",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/df358b2a36f44e3fae813759d29bc384-512x384.jpg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/df358b2a36f44e3fae813759d29bc384-512x512.jpg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/df358b2a36f44e3fae813759d29bc384\/",
        "width": "800",
        "height": "600",
        "tags": "airplane,physics,relaxing,arcade,3d,Kids Friendly,No Blood,No Cruelty",
        "views": 18,
        "upvote": 0,
        "downvote": 0,
        "slug": "paperly-paper-plane-adventure",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 191,
        "createdDate": "2024-09-30",
        "title": "Gem Clicker",
        "description": "Gem clicker is a unique but simple clicker game, click on the big gem to get money and eventually break it. Click on the four small gems to charge them up until they generate income for a small amount of time automatically. Upgrade your click DMG, get an auto-clicker, upgrade the small gems, and get a reward for each big gem broken. This game has no end and you can infinitely upgrade as the big gems get progressively harder and harder to break.",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/EKC38\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/EKC38\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/gem-clicker\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 12,
        "upvote": 0,
        "downvote": 0,
        "slug": "gem-clicker",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 174,
        "createdDate": "2024-09-30",
        "title": "Cube Stories: Escape",
        "description": "Immerse yourself in a fascinating plot and follow a brave video blogger who bravely goes into the dark embrace of an abandoned mansion. As you make your way through each carefully designed room, you'll encounter a series of cryptic puzzles and mind-bending challenges that will test your intelligence, observation, and creative thinking.\nAs the plot develops, you will be plunged into the darkness of the house's past and the mysterious history of its former inhabitants.",
        "instructions": "The goal of the game is to escape from the room. In order to get out of the room, you need to solve all the riddles and puzzles.\nIn order to interact with an object, you need to click on it or move it.",
        "category": "Puzzle",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/a7a694adc5a0409b9a8947661d61c6cf-512x384.jpg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/a7a694adc5a0409b9a8947661d61c6cf-512x512.jpg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/a7a694adc5a0409b9a8947661d61c6cf\/",
        "width": "800",
        "height": "600",
        "tags": "1player,characters,escape,horror,logic",
        "views": 10,
        "upvote": 0,
        "downvote": 0,
        "slug": "cube-stories-escape",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 182,
        "createdDate": "2024-09-30",
        "title": "Macagi Adventures",
        "description": "Macagi Adventures is an online game that you can play in modern browsers for free.",
        "instructions": "",
        "category": "Adventure",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/57A50\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/57A50\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/macagi-adventures\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 12,
        "upvote": 0,
        "downvote": 0,
        "slug": "macagi-adventures",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 208,
        "createdDate": "2024-09-30",
        "title": "Fall Words",
        "description": "This game is an ideal example of hard physics puzzle games.\n\nThe goal of the game is simple \u2014 to collect all the stars by falling words. To do this you need to be a typing master: type letters in the right places and drop them by pressing enter!\n\nLetters have different shapes and physics and based on that there are various mechanics in the game: bridge, domino, hanging, rolling and more!\n\nYou can come up with your solution, so be creative and don't be afraid to think outside the box! Unlike other brain teaser games with repetitive levels, I have designed each puzzle to be unique and challenging.\n\nThis is also a romantic puzzle game with a love story behind it! A male alien met a female alien and exchanged contact with her and they proceeded conversation in a Messenger. To answer correctly a player must type the right letters and after sending the message the letters will fall like physical objects. There are stars in the game levels that a player must collect by the falling letters. If all the stars are collected, the message is positive and the level is completed.\n\nIt is not only a physics puzzle game for adults but can be equally enjoyed by all age groups. If you are a fan of good puzzle games like \u201cbrain it on\u201d, and \u201cbrain dots\u201d this physics-based game is made for you.\n\nI hope you enjoy Fall Words!",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/080Y0\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/080Y0\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/fall-words-physics-puzzle-game\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 15,
        "upvote": 0,
        "downvote": 0,
        "slug": "fall-words",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 170,
        "createdDate": "2024-09-30",
        "title": "Block Stacking",
        "description": "Block Stacking is a very fun, leisure, and pressure-relieving game. The game is very delicate and fresh. In the game, you will play by combining many different fruits. As long as you can complete the target tasks, you will have a chance to get rewards! By eliminating the fruits on the screen, you can successfully pass the level. It's extremely easy to operate, which makes you feel very addicted. Come and try the game!",
        "instructions": "Mouse or tap to play.",
        "category": "Puzzle",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/261e725a841f473b8deb1d64a929794f-512x384.jpeg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/261e725a841f473b8deb1d64a929794f-512x512.jpeg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/261e725a841f473b8deb1d64a929794f\/",
        "width": "720",
        "height": "1280",
        "tags": "block,relaxing,3d,boys",
        "views": 15,
        "upvote": 0,
        "downvote": 0,
        "slug": "block-stacking",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 151,
        "createdDate": "2024-09-01",
        "title": "Gem Blast",
        "description": "Gem Blast",
        "instructions": "",
        "category": "Racing",
        "source": "self",
        "thumb_1": "https:\/\/play.tikgame.com\/g\/gem-blast\/icon512x512.png",
        "thumb_2": "https:\/\/play.tikgame.com\/g\/gem-blast\/icon512x512.png",
        "thumb_small": "",
        "url": "https:\/\/play.tikgame.com\/g\/gem-blast\/",
        "width": "1080",
        "height": "720",
        "tags": "",
        "views": 216,
        "upvote": 96,
        "downvote": 0,
        "slug": "angry-cat",
        "last_modified": "2024-09-25 21:28:18",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 152,
        "createdDate": "2024-09-01",
        "title": "Angry Cat",
        "description": "This cat is very annoying. The only way to make it happy is by destroying everything...",
        "instructions": "",
        "category": "Racing",
        "source": "self",
        "thumb_1": "https:\/\/play.tikgame.com\/g\/angry-cat\/icon512x512.png",
        "thumb_2": "https:\/\/play.tikgame.com\/g\/angry-cat\/icon512x512.png",
        "thumb_small": "",
        "url": "https:\/\/play.tikgame.com\/g\/angry-cat\/",
        "width": "1080",
        "height": "720",
        "tags": "",
        "views": 216,
        "upvote": 96,
        "downvote": 0,
        "slug": "angry-cat",
        "last_modified": "2024-09-25 21:28:18",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 153,
        "createdDate": "2024-09-01",
        "title": "PopCandy2025",
        "description": "PopCandy 2025",
        "instructions": "",
        "category": "Racing",
        "source": "self",
        "thumb_1": "https:\/\/play.tikgame.com\/g\/popcandy2025\/icon512x512.png",
        "thumb_2": "https:\/\/play.tikgame.com\/g\/popcandy2025\/icon512x512.png",
        "thumb_small": "",
        "url": "https:\/\/play.tikgame.com\/g\/popcandy2025\/",
        "width": "1080",
        "height": "720",
        "tags": "",
        "views": 216,
        "upvote": 96,
        "downvote": 0,
        "slug": "popcandy",
        "last_modified": "2024-09-25 21:28:18",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 192,
        "createdDate": "2024-09-30",
        "title": "Getting Over It",
        "description": "A fun strategic game made in the 19's. Then it was recreated and then remixed by me.",
        "instructions": "",
        "category": "Strategy",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/OO3GT\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/OO3GT\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/getting-over-it\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 6,
        "upvote": 0,
        "downvote": 0,
        "slug": "getting-over-it",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 220,
        "createdDate": "2024-09-30",
        "title": "Archer Arcane",
        "description": "Archer Arcane is a fantasy adventure game where you play as - you guessed it - an archer! Grab your bow and arrows, fight your way through hordes of monsters and avoid dangerous obstacles. At the end of each level, a magical upgrade awaits you.",
        "instructions": "",
        "category": "Adventure",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/7E1AC\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/7E1AC\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/archer-arcane\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 11,
        "upvote": 0,
        "downvote": 0,
        "slug": "archer-arcane",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 161,
        "createdDate": "2024-09-02",
        "title": "PopStar",
        "description": "Pop all stars to get higher scores.",
        "instructions": "Tap on 2 or more than 2 stars with the same color, stars will be erased.",
        "category": "Casual",
        "source": "remote",
        "thumb_1": "https:\/\/s.zingki.com\/g\/pop-star\/icon512x512.png",
        "thumb_2": "https:\/\/s.zingki.com\/g\/pop-star\/icon512x512.png",
        "thumb_small": "",
        "url": "https:\/\/s.zingki.com\/g\/pop-star\/",
        "width": "1080",
        "height": "720",
        "tags": "",
        "views": 355,
        "upvote": 0,
        "downvote": 0,
        "slug": "popstar",
        "last_modified": "2024-09-09 19:08:33",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 224,
        "createdDate": "2024-09-30",
        "title": "Turbo Cars Challenge",
        "description": "Take control of high-speed racing action right in the palm of your hand with our thrilling mobile game! Navigate your car through intense arena races, where every turn and every drift counts. Win heart-pounding duels against fierce opponents, showcasing your skills and dominating the competition\n\n\nUse arrow keys on keyboard to steer your car",
        "instructions": "",
        "category": "Sports",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/REB1H\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/REB1H\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/turbo-cars-challenge\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 16,
        "upvote": 0,
        "downvote": 0,
        "slug": "turbo-cars-challenge",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 164,
        "createdDate": "2024-08-31",
        "title": "Rocky Climb",
        "description": "The most challenging climbing sport. ",
        "instructions": "",
        "category": "Sport",
        "source": "remote",
        "thumb_1": "https:\/\/s.zingki.com\/g\/rocky-climb\/icon512x512.png",
        "thumb_2": "https:\/\/s.zingki.com\/g\/rocky-climb\/icon512x512.png",
        "thumb_small": "",
        "url": "https:\/\/s.zingki.com\/g\/rocky-climb",
        "width": "640",
        "height": "960",
        "tags": "",
        "views": 158,
        "upvote": 0,
        "downvote": 0,
        "slug": "rocky-climb",
        "last_modified": "2024-09-11 18:14:12",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 185,
        "createdDate": "2024-09-30",
        "title": "Crowd Enhance",
        "description": "\"Crowd Enhance\" is a casual arcade game in which you have to lead a squad of armed infantry to destroy all the enemies in your way! There are plenty of exciting levels ahead of you, in which you have to overcome various dangerous obstacles and fight against hordes of enemies trying to stop you.",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/46E63\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/46E63\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/crowd-enhance\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 12,
        "upvote": 0,
        "downvote": 0,
        "slug": "crowd-enhance",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 211,
        "createdDate": "2024-09-30",
        "title": "Flower Tile Block Puzzle",
        "description": "Welcome to Flower Tile Block Puzzle, a classic puzzle game where players must slide tiles to reassemble a picture. Move the blocks by touching or clicking on them to solve the puzzle.\n\nIn Flower Tile Block Puzzle, players are challenged to solve the puzzle by sliding tiles to reassemble a picture. The objective of the game is to move the blocks by touching or clicking on them until the picture is complete. Welcome to Flower Tile Block Puzzle and enjoy solving the puzzle.",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/8P0O8\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/8P0O8\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/flower-tile-block-puzzle\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 10,
        "upvote": 0,
        "downvote": 0,
        "slug": "flower-tile-block-puzzle",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 172,
        "createdDate": "2024-09-30",
        "title": "Fill Glass",
        "description": "Fill Glass is a simple yet addictive game. Fill the glass to the perfect level without letting it overflow or fall short of the target. Precision is key as you pour, aiming for the highest highscore!\nAs you progress, upgrade your pouring machine to enhance your accuracy!",
        "instructions": "Mobile: tap to where you want the liquid to pour to move the dispenser\nPC: Move the dispenser with mouse and click to pour the liquid",
        "category": "Casual",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/6bfc0c6ffa5b42958fd5cff50654b96c-512x384.jpg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/6bfc0c6ffa5b42958fd5cff50654b96c-512x512.jpg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/6bfc0c6ffa5b42958fd5cff50654b96c\/",
        "width": "720",
        "height": "1280",
        "tags": "2d,endless,drink,singleplayer,Kids Friendly,No Blood,No Cruelty",
        "views": 13,
        "upvote": 0,
        "downvote": 0,
        "slug": "fill-glass",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 233,
        "createdDate": "2024-09-30",
        "title": "Blocks of Puzzle",
        "description": "Do you love free block puzzle games? If you are here, then you love them! This puzzle game is reminiscent of tangram and simple puzzle, but it's completely different. I'm sure when you download Blocks of Puzzle for free, it will become one of your favorite games. Indeed, today the top games for downloading are puzzles for adults and minimalistic blocks, because we are reasonable people and we want to develop, and logic games will help us with this.\n\nBlocks of Puzzle is a simple game with a colorful design that helps train your brain. The game is brand new and with your help it will only get better every day. It seems to me that this is a great symbiosis between a person and a game, you play logic puzzles, have fun, develop logic, and in return we observe what you like and make the game even cooler. Block puzzle works for free on both phone and tablet equally well!\n\nHow to play:\nEveryone will understand our block puzzle, everything is very simple and at the same time you need to strain your brain.\nAt the bottom of the screen you have block blocks that you need to move to the top of the game in a template that you need to completely fill with these blocks.\nAfter each completed level, you are given GAMES-DK coins that can be exchanged for hints.\nNo WiFi? No problem: \"Puzzle Blocks\" refer to free games no wifi they will work even in the forest because phone games should work everywhere.\nP.S.\nContact us if you have any questions, ideas for improvement or found any bugs at dimangamedev@gmail.com",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/65ULZ\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/65ULZ\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/blocks-of-puzzle\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 11,
        "upvote": 0,
        "downvote": 0,
        "slug": "blocks-of-puzzle",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 176,
        "createdDate": "2024-09-30",
        "title": "The Skinwalker Tile Picture Challenge",
        "description": "Welcome to The Skinwalker Tile Picture Challenge, a classic puzzle game where players must slide tiles to reassemble a picture. Move the blocks by touching or clicking on them to solve the puzzle.\n\nIn The Skinwalker Tile Picture Challenge, players are challenged to solve the puzzle by sliding tiles to reassemble a picture. The objective of the game is to move the blocks by touching or clicking on them until the picture is complete. Welcome to The Skinwalker Tile Picture Challenge and enjoy solving the puzzle.",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/L5SWI\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/L5SWI\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/the-skinwalker-tile-picture-challenge\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 15,
        "upvote": 0,
        "downvote": 0,
        "slug": "the-skinwalker-tile-picture-challenge",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 225,
        "createdDate": "2024-09-30",
        "title": "Mr. Macagi Adventures",
        "description": "Embark on a daring expedition through the whimsical landscapes of Mr. Macagi's Adventure! \n\nGuide Mr. Macagi through perilous terrains, braving cunning monsters. With 4 stages set amidst the dense foliage of the forest and 4 in the unforgiving heat of the desert, prepare for a test of skill and strategy.\n\nCan you help Mr. Macagi collect apples and gold coins, and outsmart the cunning monsters that inhabit them? Explore, strategize, and conquer in this thrilling platformer adventure!",
        "instructions": "",
        "category": "Adventure",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/A56SA\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/A56SA\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/mr-macagi-adventures\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 13,
        "upvote": 0,
        "downvote": 0,
        "slug": "mr-macagi-adventures",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 162,
        "createdDate": "2024-08-31",
        "title": "Terra Infirma",
        "description": "Skate without falling over as the Earth moves beneath you! Swipe up and down as fast as you can.",
        "instructions": "",
        "category": "Adventure",
        "source": "_gamezop",
        "thumb_1": "https:\/\/static.gamezop.com\/HkBWwMUFOye\/cover.jpg",
        "thumb_2": "https:\/\/static.gamezop.com\/HkBWwMUFOye\/square.png",
        "thumb_small": "",
        "url": "https:\/\/7000.play.gamezop.com\/g\/HkBWwMUFOye",
        "width": "800",
        "height": "451",
        "tags": "",
        "views": 13,
        "upvote": 0,
        "downvote": 0,
        "slug": "terra-infirma",
        "last_modified": "2024-08-31 00:24:39",
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 238,
        "createdDate": "2024-09-30",
        "title": "Dragon's Defense Reign of Fire",
        "description": "Control the dragon, defend your kingdom against enemy invasion",
        "instructions": "",
        "category": "Adventure",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/9IER8\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/9IER8\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/dragon-s-defense-reign-of-fire\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 19,
        "upvote": 0,
        "downvote": 0,
        "slug": "dragon-s-defense-reign-of-fire",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 212,
        "createdDate": "2024-09-30",
        "title": "Popsicle Jigsaw Puzzle Quest",
        "description": "Welcome to Popsicle Jigsaw Puzzle Quest! Our Popsicle Jigsaw Puzzle Quest Puzzle Slider game is a fun and engaging way to test your visual acuity and problem-solving skills. Simply slide the images around until you find the perfect match, and watch as the puzzle pieces come together to form a beautiful Popsicle Jigsaw Puzzle Quest picture. With a wide variety of Popsicle Jigsaw Puzzle Quest images to choose from, you're sure to find something you love. So why wait? Come on in and start playing our Popsicle Jigsaw Puzzle Quest Puzzle Slider game today!\n\n",
        "instructions": "",
        "category": "Board",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/UP161\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/UP161\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/popsicle-jigsaw-puzzle-quest\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 8,
        "upvote": 0,
        "downvote": 0,
        "slug": "popsicle-jigsaw-puzzle-quest",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 165,
        "createdDate": "2024-09-30",
        "title": "Seek & Find",
        "description": "Dive into a fun puzzle hidden object game with intrigue and excitement in \"Seek &amp; Find-Hidden Object Game,\" where keen eyes and quick wits reign supreme. This scavenger hunt game invites players of all ages to find hidden objects through beautifully crafted scenes, exploring maps and secrets skillfully concealed within. With a blend of charm and challenge, this fun hidden object game is designed to captivate, entertain, and test your observational skills like never before!",
        "instructions": "Mouse\/Touchpad:\n1. Click or tap to select and highlight hidden objects.\n2. Drag to move around the scene for a better view.\n3. Scroll to zoom in and out.",
        "category": "Puzzle",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/a2253a48a7c442138467e809d61cbfcc-512x384.jpg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/a2253a48a7c442138467e809d61cbfcc-512x512.jpg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/a2253a48a7c442138467e809d61cbfcc\/",
        "width": "1920",
        "height": "1080",
        "tags": "2d",
        "views": 12,
        "upvote": 0,
        "downvote": 0,
        "slug": "seek-find",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 228,
        "createdDate": "2024-09-30",
        "title": "Bubble Shot Master",
        "description": "Bubble Shooter Master - new classic bubble shooter game in the \u201cmatch 3\u201d genre without the Internet! Play endless free offline bubbles game!\n\nShoot and pop the bubbles to create a combination of three or more balls of the same color. The more bubble balls explode in a combination, the more points you will earn in this offline puzzle game.\n\nIf shooting the balls is unsuccessful and the combination of bubbles does not come together, then you get a strike. After several strikes, a new row of multi-colored bubbles and balls appears. The match-3 game will end if the bubbles reach the bottom of the screen.\n\nThis classic match 3 bubble shooting game features beautiful super levels with unusual patterns of colorful bubbles! Pop, explode, shoot and enjoy the endless bubble shooter for free!\n\nThe puzzle game Bubble Shooter Master will appeal to children and adults, boys and girls of all ages, and those who love free match 3 games with balls and bubbles!\n\nGame Features:\n\n- Free match-3 game without internet\n- Classic bubble shooter pop\n- Unusual patterns of super levels\n- 3 difficulty levels\n- Different skins of bubbles\n- Customizable background color\n- Leaderboard and achievements",
        "instructions": "",
        "category": "Puzzle,Classics",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/HHEAU\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/HHEAU\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/bubble-shot-master-classic-bubble-shooter-match-3-game\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 17,
        "upvote": 0,
        "downvote": 0,
        "slug": "bubble-shot-master",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 173,
        "createdDate": "2024-09-30",
        "title": "Draw To Home 3D",
        "description": "Draw to home is a game to draw lines home. Everyone needs to return home according to their respective homes. This type of puzzle game is full of adventure with avoiding traps and obstacles on the way to finding a house.\n\nPlay a game of drawing a line to get home. It is very fun for children or teenagers to fill their days with this fun game.",
        "instructions": "- Touch people and draw a line to the house\n- Draw a line towards the house according to the color of the person",
        "category": "Adventure,Puzzle",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/4ffc67d23949459ab936de05eebd1da6-512x384.jpg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/4ffc67d23949459ab936de05eebd1da6-512x512.jpg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/4ffc67d23949459ab936de05eebd1da6\/",
        "width": "1920",
        "height": "1080",
        "tags": "1player,drawing,find,activity,Kids Friendly,No Blood",
        "views": 12,
        "upvote": 0,
        "downvote": 0,
        "slug": "draw-to-home-3d",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 210,
        "createdDate": "2024-09-30",
        "title": "Groot Jigsaw Tile Mania",
        "description": "Welcome to Groot Jigsaw Tile Mania! Our Groot Jigsaw Tile Mania Puzzle Slider game is a fun and engaging way to test your visual acuity and problem-solving skills. Simply slide the images around until you find the perfect match, and watch as the puzzle pieces come together to form a beautiful Groot Jigsaw Tile Mania picture. With a wide variety of Groot Jigsaw Tile Mania images to choose from, you're sure to find something you love. So why wait? Come on in and start playing our Groot Jigsaw Tile Mania Puzzle Slider game today!\n\n",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/62TW7\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/62TW7\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/groot-jigsaw-tile-mania\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 8,
        "upvote": 0,
        "downvote": 0,
        "slug": "groot-jigsaw-tile-mania",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 221,
        "createdDate": "2024-09-30",
        "title": "Crystal Flight Aztec Adventure",
        "description": "Control a flying character with a jetpack in the Aztec world, avoiding traps that can kill upon touch, collecting crystals, and fly as far as possible\n\nTo fly, press or hold down the left mouse button. On your phone, hold your finger anywhere on the screen. When you release your finger, the character descends",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/5TVE7\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/5TVE7\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/crystal-flight-aztec-adventure\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 9,
        "upvote": 0,
        "downvote": 0,
        "slug": "crystal-flight-aztec-adventure",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 197,
        "createdDate": "2024-09-30",
        "title": "Hidden Among Thieves",
        "description": "Collect loot to win the round. You can choose to be bad or greedy, but that will make you worth more to the other players &amp; may tempt them to take you down! There are plenty of hidden rooms &amp; items to help you win! Rounds get longer &amp; open up more secrets!",
        "instructions": "",
        "category": "Strategy",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/VI7D3\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/VI7D3\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/hidden-among-thieves\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 14,
        "upvote": 0,
        "downvote": 0,
        "slug": "hidden-among-thieves",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 168,
        "createdDate": "2024-09-30",
        "title": "Ocean Kids Back To School",
        "description": "Welcome to Ocean Kids Back to school. It\u2019s back to school time for these Kids. Can you help them get ready for their first day of classes? They\u2019ll need to pick some cool outfits, new hairstyles, accessories, and school supplies too in this online dress-up and design game for girls. After you\u2019re all done, help them to repair their vespa. Play and have fun! ",
        "instructions": "Left Mouse button Click",
        "category": "Art,Dress-up",
        "source": "gamedistribution",
        "thumb_1": "https:\/\/img.gamedistribution.com\/0a4b7dfd0f75461f84e79b9878b25302-512x384.jpeg",
        "thumb_2": "https:\/\/img.gamedistribution.com\/0a4b7dfd0f75461f84e79b9878b25302-512x512.jpeg",
        "thumb_small": "",
        "url": "https:\/\/html5.gamedistribution.com\/0a4b7dfd0f75461f84e79b9878b25302\/",
        "width": "800",
        "height": "600",
        "tags": "decoration,dressing",
        "views": 8,
        "upvote": 0,
        "downvote": 0,
        "slug": "ocean-kids-back-to-school",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 181,
        "createdDate": "2024-09-30",
        "title": "Granny Jigsaw Puzzle",
        "description": "Granny Jigsaw Puzzle is a fun horror puzzle game. You can select one of the nine images and then select one of the four modes (16, 36, 64 and 100 pieces). Select your favorite picture and complete the jigsaw in the shortest time possible! Have fun and enjoy!",
        "instructions": "",
        "category": "Puzzle",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/ENRLP\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/ENRLP\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/granny-jigsaw-puzzle\/embed?sid=1",
        "width": "480",
        "height": "320",
        "tags": "",
        "views": 8,
        "upvote": 0,
        "downvote": 0,
        "slug": "granny-jigsaw-puzzle",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    },
    {
        "id": 179,
        "createdDate": "2024-09-30",
        "title": "Sky Blitz",
        "description": "This game is Sky Blitz, a simple arcade game you can play anywhere.",
        "instructions": "",
        "category": "Arcade",
        "source": "gamepix",
        "thumb_1": "https:\/\/games.assets.gamepix.com\/TL145\/thumbnail\/small.png",
        "thumb_2": "https:\/\/games.assets.gamepix.com\/TL145\/thumbnail\/medium.png",
        "thumb_small": "",
        "url": "https:\/\/play.gamepix.com\/sky-blitz\/embed?sid=1",
        "width": "320",
        "height": "480",
        "tags": "",
        "views": 8,
        "upvote": 0,
        "downvote": 0,
        "slug": "sky-blitz",
        "last_modified": null,
        "is_mobile": true,
        "published": 1,
        "fields": "",
        "extra_fields": null
    }
];
